import {
  Category,
  Product,
  User,
  Order,
  Transaction,
  WalletDeposit,
  ResellerApplication,
  Coupon,
  SupportTicket,
  NotificationItem,
  AuditLog,
  SiteSettings,
} from '../types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-ai',
    name: 'AI Tools & Assistants',
    slug: 'ai-tools',
    description: 'Next-generation artificial intelligence platforms, coding assistants, and automation bots.',
    icon: 'Sparkles',
    productCount: 4,
  },
  {
    id: 'cat-productivity',
    name: 'Productivity & Office',
    slug: 'productivity',
    description: 'Workplace suites, document management, project collaboration, and workflow boosters.',
    icon: 'Briefcase',
    productCount: 3,
  },
  {
    id: 'cat-dev',
    name: 'Developer & DevOps',
    slug: 'developer-tools',
    description: 'IDE licenses, cloud runtime environments, API suites, and developer productivity tools.',
    icon: 'Terminal',
    productCount: 3,
  },
  {
    id: 'cat-cloud',
    name: 'Cloud & Storage',
    slug: 'cloud-storage',
    description: 'High-speed cloud backup, secure object storage, and synchronized drive subscriptions.',
    icon: 'Cloud',
    productCount: 2,
  },
  {
    id: 'cat-creative',
    name: 'Creative & Design',
    slug: 'creative-design',
    description: 'Digital art suites, video rendering engines, UI/UX tools, and asset libraries.',
    icon: 'Palette',
    productCount: 3,
  },
  {
    id: 'cat-security',
    name: 'Security & VPN',
    slug: 'security-vpn',
    description: 'Enterprise encryption, privacy VPN nodes, anti-malware, and identity security services.',
    icon: 'ShieldCheck',
    productCount: 2,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-ai-suite',
    name: 'NeuralCraft AI Studio',
    slug: 'neuralcraft-ai-studio',
    categoryId: 'cat-ai',
    categoryName: 'AI Tools & Assistants',
    shortDescription: 'Enterprise AI generative workspace with multimodal vision, code synthesis, and deep research agents.',
    description: 'NeuralCraft AI Studio provides access to cutting-edge multimodal intelligence models. Designed for researchers, software engineers, and digital agencies demanding high throughput, low latency token pipelines, and infinite prompt memory.',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    iconName: 'Bot',
    badge: 'Bestseller',
    rating: 4.9,
    reviewsCount: 342,
    isPopular: true,
    isFeatured: true,
    status: 'active',
    createdAt: '2026-01-15T08:00:00Z',
    plans: [
      {
        id: 'plan-ai-mo',
        name: 'Pro Tier (Monthly)',
        billingCycle: 'Monthly',
        retailPrice: 24.99,
        resellerPrice: 18.50,
        originalPrice: 30.00,
        features: ['Unlimited fast tokens', 'Multimodal Vision & Audio reasoning', 'Custom Python sandbox runner', 'Priority server queue'],
        deliveryMethod: 'Instant Key',
        deliveryTime: 'Instant (Under 60s)',
        isPopular: true,
        inStock: true,
      },
      {
        id: 'plan-ai-yr',
        name: 'Pro Tier (Yearly)',
        billingCycle: 'Yearly',
        retailPrice: 239.00,
        resellerPrice: 175.00,
        originalPrice: 299.00,
        features: ['All monthly features included', '2 months free included', 'API Webhook integration', 'Dedicated account manager'],
        deliveryMethod: 'Instant Key',
        deliveryTime: 'Instant (Under 60s)',
        inStock: true,
      },
    ],
    requirements: ['Compatible modern browser (Chrome, Firefox, Safari)', 'Valid email address for license activation link'],
    refundPolicy: 'Guaranteed 7-day refund if the digital activation key fails or cannot be redeemed.',
    faq: [
      { question: 'How is the license key delivered?', answer: 'Your activation key will be displayed directly in your order confirmation screen and saved in your customer dashboard instantly upon payment confirmation.' },
      { question: 'Is this an official authorized subscription?', answer: 'Yes. All license keys provided through SubNova are genuine digital subscriptions delivered through legitimate vendor partner channels.' },
      { question: 'Can I use this across multiple computers?', answer: 'Yes, you can sign in to your activated account on desktop, tablet, and mobile devices simultaneously.' },
    ],
  },
  {
    id: 'prod-code-master',
    name: 'CodePilot Developer Pro',
    slug: 'codepilot-developer-pro',
    categoryId: 'cat-dev',
    categoryName: 'Developer & DevOps',
    shortDescription: 'AI-assisted pair programmer IDE extension with contextual repository indexing and unit test automation.',
    description: 'Boost your software engineering speed by 40%. CodePilot indexes your entire codebase locally, predicts multiline refactors, and explains complex legacy architectures seamlessly.',
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80',
    iconName: 'Code',
    badge: 'Popular',
    rating: 4.8,
    reviewsCount: 215,
    isPopular: true,
    isFeatured: true,
    status: 'active',
    createdAt: '2026-02-01T10:00:00Z',
    plans: [
      {
        id: 'plan-code-mo',
        name: 'Individual Developer (Monthly)',
        billingCycle: 'Monthly',
        retailPrice: 16.99,
        resellerPrice: 12.00,
        originalPrice: 20.00,
        features: ['VS Code, JetBrains & Neovim plugins', 'Contextual code autocompletion', 'Repo-wide chat & refactoring', 'Private model isolation'],
        deliveryMethod: 'License Activation',
        deliveryTime: 'Instant',
        isPopular: true,
        inStock: true,
      },
      {
        id: 'plan-code-yr',
        name: 'Individual Developer (Yearly)',
        billingCycle: 'Yearly',
        retailPrice: 159.00,
        resellerPrice: 115.00,
        originalPrice: 190.00,
        features: ['Full annual license', 'Priority access to newest foundation models', 'Zero latency auto-suggest', 'Export license certificate'],
        deliveryMethod: 'License Activation',
        deliveryTime: 'Instant',
        inStock: true,
      },
    ],
    refundPolicy: 'Full refund within 5 days if activation fails.',
    faq: [
      { question: 'Does it support JetBrains IDEs?', answer: 'Yes! IntelliJ IDEA, PyCharm, WebStorm, and VS Code are fully supported.' },
    ],
  },
  {
    id: 'prod-cloud-drive',
    name: 'Stratosphere Cloud 2TB Vault',
    slug: 'stratosphere-cloud-2tb',
    categoryId: 'cat-cloud',
    categoryName: 'Cloud & Storage',
    shortDescription: 'Zero-knowledge encrypted cloud backup with unlimited bandwidth and seamless cross-device synchronization.',
    description: 'Store, sync, and share your largest media files, 4K video projects, and critical database dumps with client-side AES-256 encryption.',
    image: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=800&q=80',
    iconName: 'HardDrive',
    rating: 4.9,
    reviewsCount: 180,
    isPopular: true,
    isFeatured: false,
    status: 'active',
    createdAt: '2026-01-20T12:00:00Z',
    plans: [
      {
        id: 'plan-strato-1yr',
        name: '2TB Secure Storage (1 Year)',
        billingCycle: 'Yearly',
        retailPrice: 49.99,
        resellerPrice: 36.00,
        originalPrice: 70.00,
        features: ['2,000 GB dedicated NVMe space', 'End-to-end client-side encryption', 'Version history (365 days)', 'High-speed web & mobile apps'],
        deliveryMethod: 'Account Invitation',
        deliveryTime: 'Within 15 mins',
        isPopular: true,
        inStock: true,
      },
      {
        id: 'plan-strato-life',
        name: '5TB Lifetime Archive Plan',
        billingCycle: 'Lifetime',
        retailPrice: 189.00,
        resellerPrice: 140.00,
        originalPrice: 350.00,
        features: ['5,000 GB permanent capacity', 'No recurring annual fees', 'Direct S3-compatible API access', 'Priority node transfer'],
        deliveryMethod: 'Account Invitation',
        deliveryTime: 'Within 30 mins',
        inStock: true,
      },
    ],
    refundPolicy: 'Full refund within 14 days of activation.',
    faq: [
      { question: 'Is bandwidth capped?', answer: 'No, downloads and uploads enjoy unmetered speeds up to 10 Gbps.' },
    ],
  },
  {
    id: 'prod-pixel-studio',
    name: 'VividVector Creator Suite',
    slug: 'vividvector-creator-suite',
    categoryId: 'cat-creative',
    categoryName: 'Creative & Design',
    shortDescription: 'Professional vector graphics, raster photo editing, and motion animation studio for creative teams.',
    description: 'The preferred software suite for digital illustrators and UI designers. Includes GPU-accelerated raster brushes, non-destructive vector layers, and font management.',
    image: 'https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=800&q=80',
    iconName: 'Image',
    badge: 'Hot Deal',
    rating: 4.7,
    reviewsCount: 149,
    isPopular: false,
    isFeatured: true,
    status: 'active',
    createdAt: '2026-02-05T14:00:00Z',
    plans: [
      {
        id: 'plan-vivid-yr',
        name: 'Commercial Creator (1 Year)',
        billingCycle: 'Yearly',
        retailPrice: 79.99,
        resellerPrice: 58.00,
        originalPrice: 120.00,
        features: ['Full application suite (Mac/Windows/iPad)', 'Commercial use monetization license', 'Cloud brush & asset sync', '4K export without watermark'],
        deliveryMethod: 'Instant Key',
        deliveryTime: 'Instant',
        isPopular: true,
        inStock: true,
      },
    ],
    refundPolicy: 'Standard 7-day money-back guarantee.',
    faq: [{ question: 'Does it work offline?', answer: 'Yes, once activated offline mode operates smoothly.' }],
  },
  {
    id: 'prod-taskflow',
    name: 'TaskMatrix Enterprise Suite',
    slug: 'taskmatrix-enterprise-suite',
    categoryId: 'cat-productivity',
    categoryName: 'Productivity & Office',
    shortDescription: 'Collaborative workspaces, Gantt milestone tracking, automated sprint boards, and team documentation.',
    description: 'Consolidate Notion, Jira, and Asana into one blazing fast unified workspace. TaskMatrix empowers remote teams to organize projects, run standups, and generate executive summaries.',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
    iconName: 'Kanban',
    rating: 4.8,
    reviewsCount: 164,
    isPopular: true,
    isFeatured: false,
    status: 'active',
    createdAt: '2026-01-10T11:00:00Z',
    plans: [
      {
        id: 'plan-task-mo',
        name: 'Team Plan (5 Seats, Monthly)',
        billingCycle: 'Monthly',
        retailPrice: 29.99,
        resellerPrice: 22.00,
        originalPrice: 45.00,
        features: ['5 Member collaborative seats', 'Unlimited boards & timeline roadmaps', 'Automated GitHub & Slack sync', 'Audit log exports'],
        deliveryMethod: 'License Activation',
        deliveryTime: 'Instant',
        isPopular: true,
        inStock: true,
      },
      {
        id: 'plan-task-yr',
        name: 'Team Plan (5 Seats, Yearly)',
        billingCycle: 'Yearly',
        retailPrice: 289.00,
        resellerPrice: 210.00,
        originalPrice: 390.00,
        features: ['Full 12 months access', 'Dedicated onboarding support', 'Custom domain white-labeling', 'SLA 99.9% uptime guarantee'],
        deliveryMethod: 'License Activation',
        deliveryTime: 'Instant',
        inStock: true,
      },
    ],
    refundPolicy: 'Full refund within 7 days if you are not satisfied.',
    faq: [{ question: 'Can I add extra seats later?', answer: 'Yes, workspace owners can upgrade seat quotas at any time.' }],
  },
  {
    id: 'prod-vpn-guard',
    name: 'QuantumShield VPN Ultra',
    slug: 'quantumshield-vpn-ultra',
    categoryId: 'cat-security',
    categoryName: 'Security & VPN',
    shortDescription: 'Military-grade WireGuard encryption, 10Gbps dedicated nodes across 95+ countries, and strict zero-logging.',
    description: 'Protect your IP identity and bypass ISP bandwidth throttling with high-speed quantum-resistant encrypted tunnels.',
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80',
    iconName: 'Shield',
    rating: 4.9,
    reviewsCount: 310,
    isPopular: true,
    isFeatured: true,
    status: 'active',
    createdAt: '2026-01-25T15:00:00Z',
    plans: [
      {
        id: 'plan-vpn-1yr',
        name: '1-Year Unlimited Security',
        billingCycle: 'Yearly',
        retailPrice: 39.99,
        resellerPrice: 28.00,
        originalPrice: 89.00,
        features: ['10 Simultaneous devices', '95+ Country server locations', 'Dedicated P2P streaming nodes', 'Ad & malware blocker included'],
        deliveryMethod: 'Instant Key',
        deliveryTime: 'Instant',
        isPopular: true,
        inStock: true,
      },
      {
        id: 'plan-vpn-2yr',
        name: '2-Year Ultimate Privacy Pack',
        billingCycle: 'Yearly',
        retailPrice: 59.99,
        resellerPrice: 42.00,
        originalPrice: 140.00,
        features: ['24 Months total coverage', 'Static residential IP option', 'Multi-hop cascading VPN', 'Zero-log audited protocol'],
        deliveryMethod: 'Instant Key',
        deliveryTime: 'Instant',
        inStock: true,
      },
    ],
    refundPolicy: '30-day money-back guarantee.',
    faq: [{ question: 'Does this work for video streaming?', answer: 'Yes, dedicated 4K ultra-low buffer streaming servers are available.' }],
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user-cust-1',
    name: 'Alex Rivera',
    email: 'alex.customer@example.com',
    phone: '+1 (555) 234-5678',
    role: 'customer',
    status: 'active',
    walletBalance: 75.50,
    commissionBalance: 12.45,
    referralCode: 'ALEX789',
    createdAt: '2026-01-10T12:00:00Z',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 'user-resell-1',
    name: 'Apex Digital Hub (Sam Chen)',
    email: 'sam.reseller@example.com',
    phone: '+1 (555) 987-6543',
    role: 'reseller',
    status: 'active',
    walletBalance: 420.00,
    commissionBalance: 34.80,
    referralCode: 'APEXDIGITAL',
    createdAt: '2026-01-05T09:30:00Z',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    resellerDetails: {
      businessName: 'Apex Digital Subscriptions LLC',
      country: 'United States',
      website: 'https://apexdigital.store',
      applicationStatus: 'approved',
      discountRate: 0.25,
      totalProfit: 684.50,
      activationFeePaid: 300,
      activatedAt: '2026-01-06T10:15:00Z',
    },
  },
  {
    id: 'user-admin-1',
    name: 'Sourov Admin (Super Administrator)',
    email: 'admin@subnova.io',
    phone: '+880 1712-345678',
    role: 'admin',
    status: 'active',
    walletBalance: 12500.00,
    commissionBalance: 0,
    referralCode: 'SOUROV_MASTER',
    createdAt: '2026-01-01T00:00:00Z',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
  },
];

export const INITIAL_ADMIN_ACCOUNT = {
  username: 'sourovadmin',
  // SHA-256 hash placeholder for default password 'sourov22' (with salt 'subnova_secure_salt_v1')
  // Hashing will also verify and re-hash seamlessly in the security helper
  passwordHash: '8e815bfa802613d9a0d8bb092040dd302521d8b99c7336cc7e148e64c3917411',
  salt: 'subnova_secure_salt_v1',
  updatedAt: '2026-01-01T00:00:00Z',
};

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    orderNumber: 'SN-2026-8942',
    customerId: 'user-cust-1',
    customerName: 'Alex Rivera',
    customerEmail: 'alex.customer@example.com',
    customerPhone: '+880 1711-223344',
    productId: 'prod-ai-suite',
    productName: 'NeuralCraft AI Studio',
    productImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    planId: 'plan-ai-mo',
    planName: 'Pro Tier (Monthly)',
    billingCycle: 'Monthly',
    quantity: 1,
    unitPrice: 24.99,
    subtotal: 24.99,
    discountAmount: 2.50,
    totalAmount: 22.49,
    currency: 'USD',
    exchangeRateUsed: 120,
    totalAmountInUSD: 22.49,
    totalAmountInBDT: 2698.80,
    paymentMethod: 'card',
    paymentStatus: 'paid',
    orderStatus: 'completed',
    deliveryMethod: 'Instant Key',
    deliveryDetails: {
      licenseKey: 'NC-AI-8894-F29A-KL09-PRO',
      instructions: 'Sign in to https://app.neuralcraft.ai/redeem and enter this license key to unlock your Pro subscription tier.',
      accountEmail: 'alex.customer@example.com',
      deliveredAt: '2026-02-18T14:22:10Z',
    },
    internalNotes: 'Automated fulfillment executed successfully via API.',
    timeline: [
      { status: 'pending', title: 'Order Placed', description: 'Customer initiated checkout for NeuralCraft AI Studio', timestamp: '2026-02-18T14:20:00Z', completed: true },
      { status: 'payment_confirmed', title: 'Payment Confirmed', description: 'Payment of $22.49 processed via Stripe Card', timestamp: '2026-02-18T14:21:05Z', completed: true },
      { status: 'processing', title: 'Key Generating', description: 'Allocating official vendor partner license code', timestamp: '2026-02-18T14:21:30Z', completed: true },
      { status: 'completed', title: 'Order Completed & Delivered', description: 'License delivered to customer dashboard and email', timestamp: '2026-02-18T14:22:10Z', completed: true },
    ],
    createdAt: '2026-02-18T14:20:00Z',
    updatedAt: '2026-02-18T14:22:10Z',
  },
  {
    id: 'ord-1004',
    orderNumber: 'SN-2026-9104',
    customerId: 'user-cust-1',
    customerName: 'Tanvir Hossain',
    customerEmail: 'tanvir.dev@gmail.com',
    customerPhone: '01712998877',
    productId: 'prod-code-master',
    productName: 'CodePilot Developer Pro',
    productImage: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80',
    planId: 'plan-code-yr',
    planName: 'Individual Developer (Yearly)',
    billingCycle: 'Yearly',
    quantity: 1,
    unitPrice: 159.00,
    subtotal: 159.00,
    discountAmount: 0,
    totalAmount: 19080.00,
    currency: 'BDT',
    exchangeRateUsed: 120,
    totalAmountInUSD: 159.00,
    totalAmountInBDT: 19080.00,
    paymentMethod: 'bkash',
    paymentStatus: 'review',
    orderStatus: 'payment_review',
    deliveryMethod: 'Instant Key',
    paymentDetails: {
      senderNumber: '01712998877',
      transactionId: '9K8J2LM3Q1',
      screenshotUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=600&q=80',
      submittedAt: '2026-02-27T08:15:00Z',
    },
    timeline: [
      { status: 'pending', title: 'Order Created', description: 'Customer selected bKash payment method', timestamp: '2026-02-27T08:10:00Z', completed: true },
      { status: 'payment_review', title: 'Payment Submitted for Verification', description: 'bKash TrxID: 9K8J2LM3Q1 submitted by 01712998877', timestamp: '2026-02-27T08:15:00Z', completed: true },
      { status: 'processing', title: 'Awaiting Admin Verification', description: 'Our verification team is matching bKash statement', timestamp: 'Pending', completed: false },
      { status: 'completed', title: 'License Dispatch', description: 'Will be delivered automatically once approved', timestamp: 'Pending', completed: false },
    ],
    createdAt: '2026-02-27T08:10:00Z',
    updatedAt: '2026-02-27T08:15:00Z',
  },
  {
    id: 'ord-1005',
    orderNumber: 'SN-2026-9105',
    customerId: 'user-cust-1',
    customerName: 'Rahim Chowdhury',
    customerEmail: 'rahim.tech@yahoo.com',
    customerPhone: '01844556677',
    productId: 'prod-ai-suite',
    productName: 'NeuralCraft AI Studio',
    productImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    planId: 'plan-ai-mo',
    planName: 'Pro Tier (Monthly)',
    billingCycle: 'Monthly',
    quantity: 1,
    unitPrice: 24.99,
    subtotal: 24.99,
    discountAmount: 0,
    totalAmount: 24.99,
    currency: 'USD',
    exchangeRateUsed: 120,
    totalAmountInUSD: 24.99,
    totalAmountInBDT: 2998.80,
    paymentMethod: 'usdt_bep20',
    paymentStatus: 'review',
    orderStatus: 'payment_review',
    deliveryMethod: 'Instant Key',
    paymentDetails: {
      senderWallet: '0x39aB4F12d3C89Ef40182Ba7B337bA9C8D91970Ac',
      transactionId: '0x8f2a1b9c4d3e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a',
      screenshotUrl: 'https://images.unsplash.com/photo-1621416894569-0f39ed31d247?auto=format&fit=crop&w=600&q=80',
      submittedAt: '2026-02-27T09:20:00Z',
    },
    timeline: [
      { status: 'pending', title: 'Order Created', description: 'Customer chose USDT BEP20 cryptocurrency payment', timestamp: '2026-02-27T09:15:00Z', completed: true },
      { status: 'payment_review', title: 'Crypto Proof Submitted', description: 'TXID 0x8f2a... submitted with transaction screenshot', timestamp: '2026-02-27T09:20:00Z', completed: true },
      { status: 'processing', title: 'Blockchain Verification', description: 'Verifying on BNB Smart Chain explorer', timestamp: 'Pending', completed: false },
      { status: 'completed', title: 'License Dispatch', description: 'Key will generate instantly upon approval', timestamp: 'Pending', completed: false },
    ],
    createdAt: '2026-02-27T09:15:00Z',
    updatedAt: '2026-02-27T09:20:00Z',
  },
  {
    id: 'ord-1002',
    orderNumber: 'SN-2026-8943',
    customerId: 'user-cust-1',
    customerName: 'Alex Rivera',
    customerEmail: 'alex.customer@example.com',
    customerPhone: '+880 1711-223344',
    productId: 'prod-vpn-guard',
    productName: 'QuantumShield VPN Ultra',
    productImage: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80',
    planId: 'plan-vpn-1yr',
    planName: '1-Year Unlimited Security',
    billingCycle: 'Yearly',
    quantity: 1,
    unitPrice: 39.99,
    subtotal: 39.99,
    discountAmount: 0,
    totalAmount: 39.99,
    currency: 'USD',
    exchangeRateUsed: 120,
    totalAmountInUSD: 39.99,
    totalAmountInBDT: 4798.80,
    paymentMethod: 'wallet',
    paymentStatus: 'paid',
    orderStatus: 'completed',
    deliveryMethod: 'Instant Key',
    deliveryDetails: {
      licenseKey: 'QSVPN-2026-9921-UNLTD-NODE',
      instructions: 'Download QuantumShield app, select "Enter License Code", and paste code.',
      deliveredAt: '2026-02-22T09:12:00Z',
    },
    timeline: [
      { status: 'pending', title: 'Order Placed', description: 'Order created', timestamp: '2026-02-22T09:10:00Z', completed: true },
      { status: 'payment_confirmed', title: 'Payment Confirmed', description: 'Deducted $39.99 from Wallet balance', timestamp: '2026-02-22T09:10:15Z', completed: true },
      { status: 'processing', title: 'Fulfillment Active', description: 'Assigning WireGuard credential profile', timestamp: '2026-02-22T09:11:00Z', completed: true },
      { status: 'completed', title: 'Delivered', description: 'Activation credentials ready in portal', timestamp: '2026-02-22T09:12:00Z', completed: true },
    ],
    createdAt: '2026-02-22T09:10:00Z',
    updatedAt: '2026-02-22T09:12:00Z',
  },
  {
    id: 'ord-1002',
    orderNumber: 'SN-2026-8943',
    customerId: 'user-cust-1',
    customerName: 'Alex Rivera',
    customerEmail: 'alex.customer@example.com',
    productId: 'prod-vpn-guard',
    productName: 'QuantumShield VPN Ultra',
    productImage: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80',
    planId: 'plan-vpn-1yr',
    planName: '1-Year Unlimited Security',
    billingCycle: 'Yearly',
    quantity: 1,
    unitPrice: 39.99,
    subtotal: 39.99,
    discountAmount: 0,
    totalAmount: 39.99,
    currency: 'USD',
    exchangeRateUsed: 120,
    totalAmountInUSD: 39.99,
    totalAmountInBDT: 4798.80,
    paymentMethod: 'wallet',
    paymentStatus: 'paid',
    orderStatus: 'completed',
    deliveryMethod: 'Instant Key',
    deliveryDetails: {
      licenseKey: 'QSVPN-2026-9921-UNLTD-NODE',
      instructions: 'Download QuantumShield app, select "Enter License Code", and paste code.',
      deliveredAt: '2026-02-22T09:12:00Z',
    },
    timeline: [
      { status: 'pending', title: 'Order Placed', description: 'Order created', timestamp: '2026-02-22T09:10:00Z', completed: true },
      { status: 'payment_confirmed', title: 'Payment Confirmed', description: 'Deducted $39.99 from Wallet balance', timestamp: '2026-02-22T09:10:15Z', completed: true },
      { status: 'processing', title: 'Fulfillment Active', description: 'Assigning WireGuard credential profile', timestamp: '2026-02-22T09:11:00Z', completed: true },
      { status: 'completed', title: 'Delivered', description: 'Activation credentials ready in portal', timestamp: '2026-02-22T09:12:00Z', completed: true },
    ],
    createdAt: '2026-02-22T09:10:00Z',
    updatedAt: '2026-02-22T09:12:00Z',
  },
  {
    id: 'ord-1003',
    orderNumber: 'SN-2026-8944',
    customerId: 'user-cust-1',
    customerName: 'Alex Rivera',
    customerEmail: 'alex.customer@example.com',
    resellerId: 'user-resell-1',
    resellerName: 'Apex Digital Hub',
    productId: 'prod-code-master',
    productName: 'CodePilot Developer Pro',
    productImage: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80',
    planId: 'plan-code-yr',
    planName: 'Individual Developer (Yearly)',
    billingCycle: 'Yearly',
    quantity: 1,
    unitPrice: 159.00,
    subtotal: 159.00,
    discountAmount: 0,
    totalAmount: 159.00,
    currency: 'USD',
    exchangeRateUsed: 120,
    totalAmountInUSD: 159.00,
    totalAmountInBDT: 19080.00,
    resellerCost: 115.00,
    resellerProfit: 44.00,
    paymentMethod: 'wallet',
    paymentStatus: 'paid',
    orderStatus: 'processing',
    deliveryMethod: 'License Activation',
    internalNotes: 'Reseller bulk dispatch for customer client.',
    timeline: [
      { status: 'pending', title: 'Order Placed', description: 'Reseller submitted order for client alex.customer@example.com', timestamp: '2026-02-26T11:00:00Z', completed: true },
      { status: 'payment_confirmed', title: 'Wallet Deducted', description: 'Reseller wholesale rate ($115.00) deducted from Apex wallet', timestamp: '2026-02-26T11:00:05Z', completed: true },
      { status: 'processing', title: 'Allocating Developer Key', description: 'Manual vendor API handshake in progress', timestamp: '2026-02-26T11:05:00Z', completed: true },
      { status: 'completed', title: 'Awaiting Delivery Dispatch', description: 'Staff finalizing seat assignment', timestamp: 'Pending', completed: false },
    ],
    createdAt: '2026-02-26T11:00:00Z',
    updatedAt: '2026-02-26T11:05:00Z',
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-501',
    userId: 'user-cust-1',
    userName: 'Alex Rivera',
    type: 'deposit',
    amount: 100.00,
    currency: 'USD',
    balanceBefore: 0.00,
    balanceAfter: 100.00,
    referenceId: 'dep-101',
    description: 'Wallet top-up via Credit Card (Instant)',
    status: 'completed',
    createdAt: '2026-02-15T10:00:00Z',
  },
  {
    id: 'tx-502',
    userId: 'user-cust-1',
    userName: 'Alex Rivera',
    type: 'order_payment',
    amount: -39.99,
    currency: 'USD',
    balanceBefore: 100.00,
    balanceAfter: 60.01,
    referenceId: 'ord-1002',
    description: 'Payment for Order #SN-2026-8943 (QuantumShield VPN)',
    status: 'completed',
    createdAt: '2026-02-22T09:10:15Z',
  },
  {
    id: 'tx-503',
    userId: 'user-cust-1',
    userName: 'Alex Rivera',
    type: 'adjustment',
    amount: 15.49,
    currency: 'USD',
    balanceBefore: 60.01,
    balanceAfter: 75.50,
    referenceId: 'adj-01',
    description: 'Promotional loyalty credit bonus',
    status: 'completed',
    createdAt: '2026-02-24T12:00:00Z',
  },
  {
    id: 'tx-504',
    userId: 'user-resell-1',
    userName: 'Sam Chen',
    type: 'deposit',
    amount: 500.00,
    currency: 'USD',
    balanceBefore: 35.00,
    balanceAfter: 535.00,
    referenceId: 'dep-102',
    description: 'Wholesale Deposit via Bank Wire Transfer #WF-88912',
    status: 'completed',
    createdAt: '2026-02-20T16:00:00Z',
  },
  {
    id: 'tx-505',
    userId: 'user-resell-1',
    userName: 'Sam Chen',
    type: 'order_payment',
    amount: -115.00,
    currency: 'USD',
    balanceBefore: 535.00,
    balanceAfter: 420.00,
    referenceId: 'ord-1003',
    description: 'Wholesale fulfillment for CodePilot Developer Pro (Yearly)',
    status: 'completed',
    createdAt: '2026-02-26T11:00:05Z',
  },
];

export const INITIAL_DEPOSITS: WalletDeposit[] = [
  {
    id: 'dep-101',
    depositNumber: 'DEP-2026-01',
    userId: 'user-cust-1',
    userName: 'Alex Rivera',
    userEmail: 'alex.customer@example.com',
    amount: 100.00,
    amountBDT: 12000,
    currency: 'USD',
    paymentMethod: 'card',
    transactionRef: 'ch_3M9xYz2eZvKYlo2C1gJ',
    status: 'approved',
    adminNotes: 'Automated gateway approval',
    createdAt: '2026-02-15T10:00:00Z',
    reviewedAt: '2026-02-15T10:00:05Z',
  },
  {
    id: 'dep-102',
    depositNumber: 'DEP-2026-02',
    userId: 'user-resell-1',
    userName: 'Sam Chen',
    userEmail: 'sam.reseller@example.com',
    amount: 500.00,
    amountBDT: 60000,
    currency: 'USD',
    paymentMethod: 'bank_transfer',
    transactionRef: 'WIRE-US-9988271',
    proofNote: 'Wire transfer sent from Chase Business account ending in 4410.',
    status: 'approved',
    adminNotes: 'Verified funds received in Citibank Master Account.',
    createdAt: '2026-02-20T15:30:00Z',
    reviewedAt: '2026-02-20T16:00:00Z',
  },
  {
    id: 'dep-103',
    depositNumber: 'DEP-2026-03',
    userId: 'user-resell-1',
    userName: 'Sam Chen',
    userEmail: 'sam.reseller@example.com',
    amount: 250.00,
    amountBDT: 30000,
    currency: 'USD',
    paymentMethod: 'crypto',
    transactionRef: 'tx_hash_0x8f2a1b9c4d3e7f8a9b0c1d2e3f4a5b6c7d8e9f0a',
    proofNote: 'USDT TRC-20 transfer of 250 USDT to SubNova vault address.',
    status: 'pending',
    createdAt: '2026-02-26T18:40:00Z',
  },
];

export const INITIAL_RESELLER_APPLICATIONS: ResellerApplication[] = [
  {
    id: 'app-301',
    userId: 'user-resell-1',
    name: 'Sam Chen',
    email: 'sam.reseller@example.com',
    phone: '+1 (555) 987-6543',
    businessName: 'Apex Digital Subscriptions LLC',
    country: 'United States',
    website: 'https://apexdigital.store',
    reason: 'We operate an IT software consulting firm providing developers and digital agencies with bundled cloud services and development tools.',
    expectedVolume: '$2,000 - $5,000 / month',
    activationFee: 300,
    paymentMethod: 'wallet',
    transactionRef: 'ACT-WALLET-AUTO',
    status: 'approved',
    adminFeedback: 'Verified business registration and clean track record. Upgraded to 25% wholesale discount tier.',
    createdAt: '2026-01-05T09:30:00Z',
    reviewedAt: '2026-01-06T10:15:00Z',
  },
  {
    id: 'app-302',
    userId: 'user-pending-reseller',
    name: 'Marcus Vance',
    email: 'marcus.vance@digitalstack.io',
    phone: '+44 20 7946 0912',
    businessName: 'DigitalStack Solutions UK',
    country: 'United Kingdom',
    website: 'https://digitalstack.io',
    reason: 'Reselling developer licenses to corporate and enterprise clients.',
    expectedVolume: '$1,000 - $2,500 / month',
    activationFee: 300,
    paymentMethod: 'bkash',
    senderPhone: '01712998877',
    transactionRef: 'BKASH9921',
    status: 'pending',
    createdAt: '2026-02-26T14:20:00Z',
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'cp-01',
    code: 'WELCOME10',
    discountType: 'percentage',
    discountValue: 10,
    minOrderAmount: 15,
    maxDiscount: 20,
    expiryDate: '2026-12-31T23:59:59Z',
    usageLimit: 500,
    usageCount: 84,
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cp-02',
    code: 'SUBNOWA20',
    discountType: 'fixed',
    discountValue: 20,
    minOrderAmount: 80,
    expiryDate: '2026-12-31T23:59:59Z',
    usageLimit: 200,
    usageCount: 39,
    isActive: true,
    createdAt: '2026-01-05T00:00:00Z',
  },
  {
    id: 'cp-03',
    code: 'SPRINGAI',
    discountType: 'percentage',
    discountValue: 15,
    applicableCategoryIds: ['cat-ai', 'cat-dev'],
    minOrderAmount: 20,
    expiryDate: '2026-06-30T23:59:59Z',
    usageLimit: 1000,
    usageCount: 152,
    isActive: true,
    createdAt: '2026-02-01T00:00:00Z',
  },
];

export const INITIAL_SUPPORT_TICKETS: SupportTicket[] = [
  {
    id: 'tkt-801',
    ticketNumber: 'TKT-2026-4401',
    userId: 'user-cust-1',
    userName: 'Alex Rivera',
    userEmail: 'alex.customer@example.com',
    userRole: 'customer',
    category: 'Fulfillment',
    subject: 'Activation question for NeuralCraft AI key',
    priority: 'medium',
    status: 'resolved',
    createdAt: '2026-02-18T15:00:00Z',
    updatedAt: '2026-02-18T16:20:00Z',
    messages: [
      {
        id: 'msg-1',
        senderId: 'user-cust-1',
        senderName: 'Alex Rivera',
        senderRole: 'customer',
        message: 'Hello, I received my license key immediately! Just wanted to confirm if this also includes access to the beta multimodal API sandbox?',
        createdAt: '2026-02-18T15:00:00Z',
      },
      {
        id: 'msg-2',
        senderId: 'user-admin-1',
        senderName: 'SubNova Support (Elena)',
        senderRole: 'admin',
        message: 'Hi Alex! Yes, your Pro Tier license includes full access to the beta multimodal sandbox. You can activate it under Account Settings -> Beta Features on the provider portal.',
        createdAt: '2026-02-18T16:20:00Z',
      },
    ],
  },
  {
    id: 'tkt-802',
    ticketNumber: 'TKT-2026-4402',
    userId: 'user-resell-1',
    userName: 'Sam Chen',
    userEmail: 'sam.reseller@example.com',
    userRole: 'reseller',
    category: 'Reseller Inquiry',
    subject: 'Inquiry regarding bulk 50+ licenses for TaskMatrix Enterprise',
    priority: 'high',
    status: 'open',
    createdAt: '2026-02-26T17:15:00Z',
    updatedAt: '2026-02-26T17:15:00Z',
    messages: [
      {
        id: 'msg-3',
        senderId: 'user-resell-1',
        senderName: 'Sam Chen',
        senderRole: 'reseller',
        message: 'Hi Admin team, we have a corporate client requesting 50 yearly seats for TaskMatrix Enterprise next week. Can we arrange a custom volume discount tier beyond the standard 25%?',
        createdAt: '2026-02-26T17:15:00Z',
      },
    ],
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    userId: 'user-cust-1',
    title: 'Order Completed & Delivered',
    message: 'Your order #SN-2026-8942 for NeuralCraft AI Studio has been successfully fulfilled. Click to view license keys.',
    type: 'order',
    isRead: false,
    link: '/dashboard/orders/ord-1001',
    createdAt: '2026-02-18T14:22:10Z',
  },
  {
    id: 'notif-2',
    userId: 'user-resell-1',
    title: 'Deposit Approved',
    message: 'Your $500.00 wire transfer deposit has been approved and added to your balance.',
    type: 'wallet',
    isRead: true,
    link: '/reseller/wallet',
    createdAt: '2026-02-20T16:00:00Z',
  },
  {
    id: 'notif-3',
    userId: 'user-admin-1',
    title: 'New Reseller Application',
    message: 'Marcus Vance from DigitalStack Solutions UK submitted a reseller application.',
    type: 'reseller',
    isRead: false,
    link: '/admin/reseller-applications',
    createdAt: '2026-02-25T14:30:00Z',
  },
  {
    id: 'notif-4',
    userId: 'user-admin-1',
    title: 'Pending Crypto Deposit',
    message: 'Apex Digital submitted a 250 USDT deposit verification request.',
    type: 'wallet',
    isRead: false,
    link: '/admin/deposits',
    createdAt: '2026-02-26T18:40:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    adminId: 'user-admin-1',
    adminName: 'Elena Vance',
    action: 'APPROVE_RESELLER',
    targetType: 'reseller',
    targetId: 'app-301',
    details: 'Approved Apex Digital Subscriptions with 25% wholesale discount rate.',
    ipAddress: '192.168.1.45',
    createdAt: '2026-01-06T10:15:00Z',
  },
  {
    id: 'log-2',
    adminId: 'user-admin-1',
    adminName: 'Elena Vance',
    action: 'APPROVE_DEPOSIT',
    targetType: 'deposit',
    targetId: 'dep-102',
    details: 'Approved $500.00 bank wire deposit for Sam Chen.',
    ipAddress: '192.168.1.45',
    createdAt: '2026-02-20T16:00:00Z',
  },
  {
    id: 'log-3',
    adminId: 'user-admin-1',
    adminName: 'Elena Vance',
    action: 'CREATE_PRODUCT',
    targetType: 'product',
    targetId: 'prod-vpn-guard',
    details: 'Added QuantumShield VPN Ultra with 2 plans.',
    ipAddress: '192.168.1.45',
    createdAt: '2026-01-25T15:00:00Z',
  },
];

export const INITIAL_SETTINGS: SiteSettings = {
  siteName: 'SubNova Subscriptions',
  tagline: 'Premium Digital Subscriptions, Software Licenses & Reseller Network',
  supportEmail: 'support@subnova.io',
  whatsappSupportNumber: '+8801712345678',
  currency: 'BDT',
  currencySymbol: '৳',
  usdExchangeRate: 120, // 1 USD = 120 BDT
  resellerActivationFeeBDT: 300,
  referralCommissionRate: 5,
  commissionDestination: 'commission_wallet',
  allowPublicRegistration: true,
  allowResellerApplications: true,
  defaultResellerDiscountPercentage: 25,
  maintenanceMode: false,
  usd: {
    usdtBep20Address: '0x8f2a1b9c4d3e7f8a9b0c1d2e3f4a5b6c7d8e9f0a',
    binanceUid: '839201847',
    instructions: 'Send exact payment in USDT via BEP20 network or using Binance Pay UID. Upload transaction ID (TXID / Reference) and clear screenshot for fast verification.',
  },
  bdt: {
    bkashNumber: '01712-345678',
    bkashType: 'Personal',
    nagadNumber: '01812-345678',
    nagadType: 'Personal',
    instructions: 'bKash বা Nagad-এ উল্লিখিত নম্বরে Send Money করুন। সফল লেনদেনের পর আপনার Sender Mobile Number, TrxID ও Payment Screenshot জমা দিন।',
  },
  paymentSettings: {
    usd: {
      usdtBep20Address: '0x8f2a1b9c4d3e7f8a9b0c1d2e3f4a5b6c7d8e9f0a',
      binanceUid: '839201847',
      instructions: 'Send exact payment in USDT via BEP20 network or using Binance Pay UID. Upload transaction ID (TXID / Reference) and clear screenshot for fast verification.',
    },
    bdt: {
      bkashNumber: '01712-345678',
      bkashType: 'Personal',
      nagadNumber: '01812-345678',
      nagadType: 'Personal',
      instructions: 'bKash বা Nagad-এ উল্লিখিত নম্বরে Send Money করুন। সফল লেনদেনের পর আপনার Sender Mobile Number, TrxID ও Payment Screenshot জমা দিন।',
    },
  },
  bankPaymentDetails: {
    bankName: 'Citibank N.A. (San Francisco)',
    accountName: 'SubNova Cloud Systems Inc.',
    accountNumber: '9844-1029-3841-00',
    swiftCode: 'CITIUS33XXX',
    routingNumber: '121000358',
  },
  cryptoPaymentDetails: {
    usdtTronAddress: 'TX9Qk2m7Vz8PqL4wN1RjX7gY9sBt3dE5mA',
    btcAddress: 'bc1q9v8t6s4e2w0r8y5u3i1o7p9a6s4d2f8g0h',
    ethAddress: '0x71C...B29F4aE5',
  },
  enabledGateways: {
    stripe: true,
    paypal: true,
    crypto: true,
    bankTransfer: true,
    wallet: true,
  },
};
